stages:
  - buildweb
  - buildloadbalancer
  - unittestweb
  - commit
  - deploy

before_script:
  - apk --update add openssh-client git
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - docker info
  - git config --global user.email "dangahan@gmail.com"
  - git config --global user.name "DanGahan"

buildweb:
  stage: buildweb
  image: docker:1.11
  services:
    - docker:dind
  script:
  - export WEBVERSION=$(git rev-parse HEAD)
  - echo "export WEBBVERSION=$(echo "$WEBVERSION")" >> variables
  - ls
  - docker build -t dangahan/gahandotmedotukweb:$WEBVERSION .
  - docker login -u "$DOCKERHUBUSER" -p "$DOCKERHUBPASSWORD"
  - docker push dangahan/gahandotmedotukweb:$WEBVERSION
  artifacts:
    paths: 
    - variables 

buildloadbalancer:
  stage: buildloadbalancer
  image: docker:1.11
  services:
    - docker:dind
  script:  
  - git clone https://"$GITUSER":"$GITPASSWORD"@github.com/DanGahan/GahanDotMeDotUkLoadbalancer.git
  - cd GahanDotMeDotUkLoadbalancer
  - export LBVERSION=$(git rev-parse HEAD)
  - export LBBVERSION="$(echo "$LBVERSION")" >> variables
  - ls
  - docker build -t dangahan/gahandotmedotukloadbalancer:$LBVERSION .
  - docker login -u "$DOCKERHUBUSER" -p "$DOCKERHUBPASSWORD" 
  - docker push dangahan/gahandotmedotukloadbalancer:$LBVERSION
  artifacts:
    paths: 
     - variables 

unittestweb:
  stage: unittestweb
  image: docker:1.11
  services:
    - docker:dind
  script:
  - source variables
  - docker run --name UnitTest -p 80:80 -p 443:443 -d  dangahan/gahandotmedotukweb:\$VERSION
  - curl http://127.0.0.1:80
  artifacts:
    paths: 
     - variables

deploy: 
  stage: deploy
  image: docker:1.11
  services:
    - docker:dind
  script:  
  - source variables
  - dan@178.79.155.32 -p 2222 "cd ~/GahanDotMeDotUkCompose && /bin/sudo /bin/docker-compose down"
  - dan@178.79.155.32 -p 2222 "cd ~/GahanDotMeDotUkCompose && rm docker-compose.yml && rm .env"
  - dan@178.79.155.32 -p 2222 "git clone git@github.com:DanGahan/GahanDotMeDotUkCompose.git"
  - dan@178.79.155.32 -p 2222 "cd ~/GahanDotMeDotUkCompose && echo WEBTAG=$WEBVERSION >> .env && echo LBTAG=$LBVERSION >> .env"
  - dan@178.79.155.32 -p 2222 "cd ~/GahanDotMeDotUkCompose && /bin/sudo /bin/docker-compose up -d"   
  artifacts:
    paths: 
     - variables 

