# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Update the footer.html with latest info
      - name: update footer.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export WEBVERSION=$(git rev-parse HEAD)
          sed -i "s|XX-YEAR-XX|$(date '+%Y')|g" footer.html
          sed -i  "s|DD-MM-YYYY|$(date '+%d/%m/%Y')|g" footer.html
          sed -i  "s|XXX-XXX-XXX|$WEBVERSION|g" footer.html
          git remote add site https://github.com/DanGahan/DanGahan.github.io.git
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
          git push -u site master          
 
      # Slack Web Hook

