# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Update the footer.html with latest info
      - name: update footer.html
        run: |
          export WEBVERSION=$(git rev-parse HEAD)
          sed -i "s|20..|$(date '+%Y')|g" footer.htm
          sed -i  "s|Build Stamp.*|Build Stamp: $(date '+%d/%m/%Y')|g" footer.html
          sed -i  "s|Build Ref.*|iBuild Ref: $WEBVERSION|g" footer.html
          git config --global user.name "Automated Action"
          git config --global user.email "automatedaction@gahan.me.uk"
          git add footer.html
          git commit -m "auto commit from actions"
          git push origin master

